import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { formatTimestamp, type PlayerSelection, type Team } from '@songcollector/shared';
import { api } from '../api';
import { useAdmin } from '../AdminContext';
import { ErrorMessage, Loading } from '../components/Status';
import { useLoad } from '../hooks';

export function AdminTeamPage() {
  const { teamId = '' } = useParams(); const admin = useAdmin(); const [message, setMessage] = useState(''); const [actionError, setActionError] = useState(''); const [editing, setEditing] = useState<PlayerSelection>(); const [editingTeam, setEditingTeam] = useState(false);
  const state = useLoad(async () => { if (!admin.token) throw new Error('Enter the admin token again.'); return { team: await api.team(teamId), selections: await api.selections(teamId) }; }, [teamId, admin.token]);
  if (!admin.token) return <div className="page narrow"><ErrorMessage message="Admin access is locked because the token is held in memory only." /><Link className="button primary" to="/admin">Unlock admin</Link></div>;
  if (state.loading) return <div className="page"><Loading label="Opening lineup…" /></div>;
  if (state.error || !state.data) return <div className="page"><ErrorMessage message={state.error || 'Could not open team.'} /></div>;
  const { team, selections } = state.data as { team: Team; selections: PlayerSelection[] };
  const copy = async (text: string, label: string) => { await navigator.clipboard.writeText(text); setMessage(`${label} copied.`); };
  const remove = async (selection: PlayerSelection) => { if (!window.confirm(`Delete ${selection.playerName}'s selection?`)) return; try { await api.deleteSelection(selection.id, admin.token); state.setData({ team, selections: selections.filter((item) => item.id !== selection.id) }); setMessage('Selection deleted.'); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Delete failed.'); } };
  const save = async (selection: PlayerSelection, values: Record<string, unknown>) => { try { const result = await api.updateSelection(selection.id, values, admin.token); state.setData({ team, selections: selections.map((item) => item.id === selection.id ? result.selection : item) }); setEditing(undefined); setMessage(result.warnings[0]?.message ?? 'Selection updated.'); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Update failed.'); } };
  const saveTeam = async (values: Partial<Pick<Team, 'name' | 'slug' | 'ageDivision'>>) => { try { const updated = await api.updateTeam(team.id, values, admin.token); state.setData({ team: updated, selections }); setEditingTeam(false); setMessage('Team details updated.'); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Team update failed.'); } };
  return <div className="page"><Link className="back-link" to="/admin">← All teams</Link><section className="section-heading"><div><div className="eyebrow">Coach admin</div><h1>{team.name}</h1><p>Public link: <Link to={`/teams/${team.slug}`}>/teams/{team.slug}</Link></p></div><div className="hero-actions"><button className="button ghost" onClick={() => setEditingTeam(true)}>Edit team</button><button className="button ghost" onClick={() => void copy(`${window.location.origin}/teams/${team.slug}`, 'Team link')}>Copy team link</button><button className="button secondary" onClick={() => void api.download(team.id, 'csv', admin.token)}>Download CSV</button><button className="button secondary" onClick={() => void api.download(team.id, 'txt', admin.token)}>Download setup text</button></div></section>{message && <div className="alert success" role="status">{message}</div>}{actionError && <ErrorMessage message={actionError} />}<section><div className="section-heading"><div><h2>BallparkDJ setup</h2><p>Copy each row into your workflow. Review timing and content before game day.</p></div></div><div className="table-wrap"><table><thead><tr><th>Player</th><th>Song</th><th>Start</th><th>YouTube</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{selections.map((item) => <tr key={item.id}><td><strong>#{item.jerseyNumber}</strong> {item.playerName}</td><td>{item.songTitle}<small>{item.artist}</small></td><td>{formatTimestamp(item.startTimeSeconds) || '—'}</td><td><button className="text-button" onClick={() => void copy(item.youtubeUrl, `${item.playerName}'s link`)}>Copy link</button></td><td><div className="row-actions"><button className="text-button" onClick={() => setEditing(item)}>Edit</button><button className="text-button danger" onClick={() => void remove(item)}>Delete</button></div></td></tr>)}</tbody></table>{selections.length === 0 && <div className="empty">No selections have been submitted.</div>}</div><p className="disclaimer">BallparkDJ documentation does not establish these exports as a verified direct-import format. Treat them as setup aids.</p></section>{editing && <EditSelection selection={editing} onCancel={() => setEditing(undefined)} onSave={save} />}{editingTeam && <EditTeam team={team} onCancel={() => setEditingTeam(false)} onSave={saveTeam} />}</div>;
}

function EditSelection({ selection, onCancel, onSave }: { selection: PlayerSelection; onCancel: () => void; onSave: (selection: PlayerSelection, values: Record<string, unknown>) => Promise<void> }) {
  const [values, setValues] = useState({ playerName: selection.playerName, jerseyNumber: selection.jerseyNumber, songTitle: selection.songTitle, artist: selection.artist, youtubeUrl: selection.youtubeUrl, startTime: formatTimestamp(selection.startTimeSeconds) });
  return <div className="modal-backdrop"><form className="modal form" onSubmit={(event) => { event.preventDefault(); void onSave(selection, values); }}><button className="modal-close" type="button" aria-label="Close" onClick={onCancel}>×</button><h2>Edit selection</h2>{Object.entries(values).map(([name, value]) => <label key={name}>{({ playerName: 'Player name', jerseyNumber: 'Jersey number', songTitle: 'Song title', artist: 'Artist', youtubeUrl: 'YouTube URL', startTime: 'Start time' } as Record<string, string>)[name]}<input value={value} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} /></label>)}<button className="button primary">Save changes</button></form></div>;
}

function EditTeam({ team, onCancel, onSave }: { team: Team; onCancel: () => void; onSave: (values: Partial<Pick<Team, 'name' | 'slug' | 'ageDivision'>>) => Promise<void> }) {
  const [values, setValues] = useState({ name: team.name, slug: team.slug, ageDivision: team.ageDivision ?? '' });
  return <div className="modal-backdrop"><form className="modal form" onSubmit={(event) => { event.preventDefault(); void onSave(values); }}><button className="modal-close" type="button" aria-label="Close" onClick={onCancel}>×</button><h2>Edit team</h2><label>Team name<input value={values.name} onChange={(event) => setValues((current) => ({ ...current, name: event.target.value }))} required /></label><label>Link short name<input value={values.slug} onChange={(event) => setValues((current) => ({ ...current, slug: event.target.value }))} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label>Age / division<input value={values.ageDivision} onChange={(event) => setValues((current) => ({ ...current, ageDivision: event.target.value }))} /></label><button className="button primary">Save team</button></form></div>;
}
