import { useState } from 'react';
import { formatTimestamp, type BallparkImportAction, type BallparkImportCommitResult, type BallparkImportPreview, type BallparkImportPreviewRow } from '@songcollector/shared';
import { api, type YouTubeCandidate } from '../api';
import { ErrorMessage } from './Status';

type EditableRow = BallparkImportPreviewRow & { artist: string; youtubeUrl: string; startTime: string; action: BallparkImportAction; allowDuplicateJersey: boolean };
function editableRows(preview: BallparkImportPreview): EditableRow[] { return preview.rows.map((row) => ({ ...row, artist: row.artist ?? '', youtubeUrl: row.youtubeUrl ?? '', startTime: formatTimestamp(row.startTimeSeconds) ?? '', allowDuplicateJersey: false })); }

export function BallparkImportDialog({ teamId, token, onClose, onComplete }: { teamId: string; token: string; onClose: () => void; onComplete: () => void }) {
  const [csv, setCsv] = useState(''); const [rows, setRows] = useState<EditableRow[]>([]); const [preview, setPreview] = useState<BallparkImportPreview>(); const [result, setResult] = useState<BallparkImportCommitResult>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [candidates, setCandidates] = useState<Record<string, YouTubeCandidate[]>>({});
  const previewImport = async () => { setBusy(true); setError(''); setResult(undefined); try { const value = await api.previewBallparkImport(teamId, csv, token); setPreview(value); setRows(editableRows(value)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not read the BallparkDJ file.'); } finally { setBusy(false); } };
  const update = (rowId: string, value: Partial<EditableRow>) => setRows((current) => current.map((row) => row.rowId === rowId ? { ...row, ...value } : row));
  const searchYouTube = async (row: EditableRow) => { setBusy(true); setError(''); try { const value = await api.youtubeSearch(row.songTitle, row.artist, token); setCandidates((current) => ({ ...current, [row.rowId]: value.candidates })); if (!value.configured) setError('YouTube suggestions are not configured yet. Add YOUTUBE_API_KEY to the API; catalog matches and manual URLs still work.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'YouTube search failed.'); } finally { setBusy(false); } };
  const commit = async () => { setBusy(true); setError(''); try { const value = await api.confirmBallparkImport(teamId, rows.map((row) => ({ rowId: row.rowId, existingSelectionId: row.existingSelectionId, action: row.action, playerName: row.playerName, jerseyNumber: row.jerseyNumber, songTitle: row.songTitle, artist: row.artist, youtubeUrl: row.youtubeUrl, startTime: row.startTime, songId: row.songId, allowDuplicateJersey: row.allowDuplicateJersey })), token); setResult(value); if (value.failed.length === 0) onComplete(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not apply the import.'); } finally { setBusy(false); } };
  const renderRow = (row: EditableRow) => { const rowCandidates = candidates[row.rowId] ?? []; return <tr key={row.rowId}><td><strong>#{row.jerseyNumber}</strong><small>{row.playerName}</small></td><td>{row.songTitle}<small>CSV row {row.lineNumber}</small></td><td><span className="tag">{row.status}</span>{row.issues.map((issue) => <small key={issue}>{issue}</small>)}</td><td><input aria-label={`${row.playerName} artist`} value={row.artist} onChange={(event) => update(row.rowId, { artist: event.target.value })} /></td><td><input aria-label={`${row.playerName} YouTube URL`} value={row.youtubeUrl} onChange={(event) => update(row.rowId, { youtubeUrl: event.target.value })} placeholder="https://youtu.be/…" /><button className="text-button" type="button" disabled={busy || !row.artist} onClick={() => void searchYouTube(row)}>Find link</button>{rowCandidates.length > 0 && <select aria-label={`${row.playerName} suggestions`} onChange={(event) => update(row.rowId, { youtubeUrl: event.target.value })} defaultValue=""><option value="" disabled>Choose a suggestion</option>{rowCandidates.map((candidate) => <option key={candidate.videoId} value={candidate.url}>{candidate.title} — {candidate.channelTitle}</option>)}</select>}</td><td><input aria-label={`${row.playerName} start time`} value={row.startTime} onChange={(event) => update(row.rowId, { startTime: event.target.value })} placeholder="0:00" /></td><td><select aria-label={`${row.playerName} import action`} value={row.action} onChange={(event) => update(row.rowId, { action: event.target.value as BallparkImportAction })}><option value="create">Create</option><option value="update" disabled={!row.existingSelectionId}>Update</option><option value="skip">Skip</option></select>{row.status === 'conflict' && <label className="hint"><input type="checkbox" checked={row.allowDuplicateJersey} onChange={(event) => update(row.rowId, { allowDuplicateJersey: event.target.checked })} /> allow jersey reuse</label>}</td></tr>; };
  return <div className="modal-backdrop"><div className="modal" style={{ width: 'min(100%, 1100px)', maxHeight: '92vh', overflow: 'auto' }}><button className="modal-close" type="button" aria-label="Close" onClick={onClose}>×</button><h2>Import BallparkDJ setup</h2><p>Paste the CSV exported by BallparkDJ. SongCollector matches catalog titles, shows conflicts, and lets you confirm each change before saving.</p>{!preview && <><label className="field">CSV file<input type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) void file.text().then(setCsv); }} /></label><label className="field">Paste CSV<textarea value={csv} onChange={(event) => setCsv(event.target.value)} rows={10} style={{ width: '100%', padding: 12, border: '1px solid #bab2c6', borderRadius: 10 }} placeholder="Number,FirstName,LastName,SongName,SongStart,SongLength,SongOverlap" /></label><button className="button primary" disabled={busy || !csv.trim()} onClick={() => void previewImport()}>{busy ? 'Reading…' : 'Preview import'}</button></>}{error && <ErrorMessage message={error} />}{preview && !result && <><div className="alert success" role="status">{preview.matched} matched · {preview.unmatched} need a song link · {preview.conflicts} conflicts</div><div className="table-wrap"><table><thead><tr><th>Player</th><th>Song</th><th>Status</th><th>Artist</th><th>YouTube URL</th><th>Start</th><th>Action</th></tr></thead><tbody>{rows.map(renderRow)}</tbody></table></div><div className="hero-actions"><button className="button ghost" onClick={() => { setPreview(undefined); setRows([]); }}>Choose another file</button><button className="button primary" disabled={busy} onClick={() => void commit()}>{busy ? 'Applying…' : 'Confirm and apply'}</button></div></>}{result && <><div className="alert success" role="status">Created {result.created}, updated {result.updated}, skipped {result.skipped}, failed {result.failed.length}.</div>{result.failed.length > 0 && <div className="alert error">{result.failed.map((failure) => <div key={failure.rowId}>Row {failure.rowId}: {failure.message}</div>)}</div>}<button className="button primary" onClick={onComplete}>Done</button></>}</div></div>;
}
